dist: xenial

language: node_js

addons:
  apt:
    packages:
      - chromium-browser

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: lts/*
    - os: linux
      node_js: node
    - os: osx
      node_js: lts/*
      addons:
        firefox: latest
    - os: osx
      node_js: node
      addons:
        firefox: latest

  allow_failures:
    - os: osx

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew cask install chromium; fi

script:
  - yarn lint
  - yarn audit
  - yarn test --code-coverage

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
