language: node_js

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: lts/*
    - os: linux
      node_js: node
    - os: windows
      node_js: lts/*
    - os: windows
      node_js: node
    - os: osx
      node_js: lts/*
      addons:
        firefox: latest
    - os: osx
      node_js: node
      addons:
        firefox: latest

  allow_failures:
    - os: windows
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash -s; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then export PATH=$HOME/.yarn/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew cask install chromium; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install firefox; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install chromium --pre -y; fi

script:
  - yarn lint
  - yarn test --code-coverage

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
