language: node_js

os:
  - linux
  - windows

node_js:
  - lts/*
  - node

before_install:
- if [[ "$TRAVIS_OS_NAME" = "windows" ]]; curl -o- -L https://yarnpkg.com/install.sh | bash -s; fi
- if [[ "$TRAVIS_OS_NAME" = "windows" ]]; export PATH=$HOME/.yarn/bin:$PATH; fi

script:
  - yarn lint
  - yarn test --code-coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
