name: CI

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  FORCE_COLOR: 3

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    strategy:
      max-parallel: 4
      matrix:
        node-version: [ 22.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: npm update"
          committer: 'Michel Palourdio <mpalourdio@gmail.com>'
          author: 'Michel Palourdio <mpalourdio@gmail.com>'
          branch: 'npm-update'
          delete-branch: 'true'
          title: 'chore: npm update'
          labels: 'npm update'
